import { DataOfCaracteristicFeatureInterface } from "../types";

export const profileData: DataOfCaracteristicFeatureInterface[] = [
  {
    displayName: "getAllOrdersForProfile",
    requestParameters: [
      {
        id: "query",
        type: "string",
        required: false,
        description:
          "This field specifies the query used to limit the orders returns. Defaults to RQL. To use SCIM use the queryFormat parameter",
      },
      {
        id: "offset",
        type: "int",
        required: false,
        description: "Starting index.",
      },
      {
        id: "countOnly",
        type: "boolean",
        required: false,
        description: "Only return the count of orders for the current profile.",
      },
      {
        id: "incompleteOnly",
        type: "boolean",
        required: false,
        description:
          "Only return the list of incomplete orders for the current profile.",
      },
      {
        id: "limit",
        type: "int",
        required: false,
        description:
          "Specifies the number of orders to be retrieved starting from offset. In case this is not present, the complete list of orders for the profile is returned.",
      },
      {
        id: "sort",
        type: "string",
        required: false,
        description:
          "This field specifies the sort order of the list to be fetched.",
      },
    ],
    example: { query: "state eq 'NO_PENDING_ACTION'", offset: 0, limit: 2 },
  },
  {
    displayName: "createProfile",
    requestParameters: [
      {
        id: "firstName",
        type: "string",
        required: true,
        description: "The first name of the profile.",
      },
      {
        id: "lastName",
        type: "string",
        required: true,
        description: "The last name of the profile.",
      },
      {
        id: "email",
        type: "string",
        required: true,
        description: "The email address of the profile.",
      },
      {
        id: "locale",
        type: "string",
        required: false,
        description: "The locale of the profile.",
      },
      {
        id: "password",
        type: "string",
        required: true,
        description: "The password of the profile.",
      },
      {
        id: "receiveEmail",
        type: "string",
        required: true,
        description:
          "The string representation of whether the user wants to receive email or not.",
      },
      {
        id: "GDPRProfileP13nConsentGranted",
        type: "boolean",
        required: false,
        description:
          "If user has given consent for his/her profile information to be used for personalization purposes.",
      },
      {
        id: "gender",
        type: "string",
        required: false,
        description: "The gender of the profile user.",
      },
      {
        id: "dateOfBirth",
        type: "string",
        required: false,
        description: "The date of birth of the profile user.",
      },
      {
        id: "shippingAddress",
        type: "object",
        required: false,
        description: "Default shipping addresses associated with profile.",
        internalPropperties: [
          {
            id: "repositoryId",
            type: "string",
            required: false,
            description: "The repository ID of the shipping address.",
          },
          {
            id: "alias",
            type: "string",
            required: false,
            description: "The alias of the shipping address.",
          },
          {
            id: "firstName",
            type: "string",
            required: true,
            description: "The first name of the shipping address.",
          },
          {
            id: "lastName",
            type: "string",
            required: true,
            description: "The last name of the shipping address.",
          },
          {
            id: "address1",
            type: "string",
            required: true,
            description: "The address line 1 of the shipping address.",
          },
          {
            id: "address2",
            type: "string",
            required: false,
            description: "The address line 2 of the shipping address.",
          },
          {
            id: "address3",
            type: "string",
            required: false,
            description: "The address line 3 of the shipping address.",
          },
          {
            id: "city",
            type: "string",
            required: true,
            description: "The city of the shipping address.",
          },
          {
            id: "county",
            type: "string",
            required: false,
            description: "The county code of the shipping address.",
          },
          {
            id: "state",
            type: "string",
            required: true,
            description: "The state code of the shipping address.",
          },
          {
            id: "postalCode",
            type: "string",
            required: true,
            description: "The postal Code of the shipping address.",
          },
          {
            id: "country",
            type: "string",
            required: true,
            description: "The country of the shipping address.",
          },
          {
            id: "isDefaultAddress",
            type: "boolean",
            required: false,
            description:
              "Whether to store this address in the default shipping address slot.",
          },
          {
            id: "phoneNumber",
            type: "string",
            required: false,
            description: "The phone Number of the shipping address.",
          },
          {
            id: "companyName",
            type: "string",
            required: false,
            description: "The company name of the shipping address.",
          },
          {
            id: "prefix",
            type: "string",
            required: false,
            description: "The prefix of the shipping address.",
          },
          {
            id: "selectedCountry",
            type: "string",
            required: false,
            description:
              "The country code of the shipping address. If selectedCountry is sent in the request then it takes precedence over country.",
          },
          {
            id: "selectedState",
            type: "string",
            required: false,
            description:
              "The state ISO alpha-2 code of the shipping address. If selectedState is sent in the request then it takes precedence over state.",
          },
          {
            id: "state_ISOCode",
            type: "string",
            required: false,
            description: "The state ISO alpha-4 code of the shipping address.",
          },
        ],
      },
      {
        id: "autoLogin",
        type: "boolean",
        required: false,
        description: "If set to true log the user in after account creation.",
      },
      {
        id: "login",
        type: "string",
        required: false,
        description:
          "The login of the profile. This can be set to allow a user to login with a username that's not an email.",
      },
    ],
    example: {
      firstName: "Sally",
      lastName: "lemon",
      email: "sally@example.com",
      locale: "en",
      password: "sally1234",
      receiveEmail: "yes",
      GDPRProfileP13nConsentGranted: true,
      gender: "female",
      dateOfBirth: "",
      _dynamicProperty_: "Dynamic Property Value",
      shippingAddress: {
        repositoryId: "1234567",
        alias: "Address",
        firstName: "Jack",
        lastName: "Black",
        address1: "405 Example Street",
        address2: "",
        address3: "",
        city: "Wake Forest",
        county: "",
        state: "North Carolina",
        postalCode: "27587",
        country: "United States",
        isDefaultAddress: true,
        phoneNumber: "555123456",
        prefix: "",
        companyName: "",
        selectedCountry: "US",
        selectedState: "NC",
        state_ISOCode: "US-NC",
      },
      shippingAddresses: [
        {
          repositoryId: "1234567",
          alias: "Address",
          firstName: "Jack",
          lastName: "Black",
          address1: "405 Example Street",
          address2: "",
          address3: "",
          city: "Wake Forest",
          county: "",
          state: "North Carolina",
          postalCode: "27587",
          country: "United States",
          isDefaultAddress: true,
          phoneNumber: "555123456",
          prefix: "",
          companyName: "",
          selectedCountry: "US",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
        {
          alias: "Address##0",
          firstName: "Jill",
          lastName: "Hill",
          address1: "415 Example Road",
          address2: "",
          address3: "",
          city: "Wake Forest",
          county: "",
          state: "North Carolina",
          postalCode: "27587",
          country: "United States",
          isDefaultAddress: false,
          phoneNumber: "55512345",
          prefix: "",
          companyName: "",
          selectedCountry: "US",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
      ],
      autoLogin: true,
      "login:": "sally.sally",
    },
  },
  {
    displayName: "registerProfile",
    requestParameters: [
      {
        id: "firstName",
        type: "string",
        required: true,
        description: "The first name of the profile.",
      },
      {
        id: "lastName",
        type: "string",
        required: true,
        description: "The last name of the profile.",
      },
      {
        id: "email",
        type: "string",
        required: true,
        description: "The email address of the profile.",
      },
      {
        id: "locale",
        type: "string",
        required: false,
        description: "The locale of the profile.",
      },
      {
        id: "password",
        type: "string",
        required: true,
        description: "The password of the profile.",
      },
      {
        id: "receiveEmail",
        type: "string",
        required: true,
        description:
          "The string representation of whether the user wants to receive email or not.",
      },
      {
        id: "GDPRProfileP13nConsentGranted",
        type: "boolean",
        required: false,
        description:
          "If user has given consent for his/her profile information to be used for personalization purposes.",
      },
      {
        id: "gender",
        type: "string",
        required: false,
        description: "The gender of the profile user.",
      },
      {
        id: "dateOfBirth",
        type: "string",
        required: false,
        description: "The date of birth of the profile user.",
      },
      {
        id: "shippingAddress",
        type: "object",
        required: false,
        description: "Default shipping addresses associated with profile.",
        internalPropperties: [
          {
            id: "repositoryId",
            type: "string",
            required: false,
            description: "The repository ID of the shipping address.",
          },
          {
            id: "alias",
            type: "string",
            required: false,
            description: "The alias of the shipping address.",
          },
          {
            id: "firstName",
            type: "string",
            required: true,
            description: "The first name of the shipping address.",
          },
          {
            id: "lastName",
            type: "string",
            required: true,
            description: "The last name of the shipping address.",
          },
          {
            id: "address1",
            type: "string",
            required: true,
            description: "The address line 1 of the shipping address.",
          },
          {
            id: "address2",
            type: "string",
            required: false,
            description: "The address line 2 of the shipping address.",
          },
          {
            id: "address3",
            type: "string",
            required: false,
            description: "The address line 3 of the shipping address.",
          },
          {
            id: "city",
            type: "string",
            required: true,
            description: "The city of the shipping address.",
          },
          {
            id: "county",
            type: "string",
            required: false,
            description: "The county code of the shipping address.",
          },
          {
            id: "state",
            type: "string",
            required: true,
            description: "The state code of the shipping address.",
          },
          {
            id: "postalCode",
            type: "string",
            required: true,
            description: "The postal Code of the shipping address.",
          },
          {
            id: "country",
            type: "string",
            required: true,
            description: "The country of the shipping address.",
          },
          {
            id: "isDefaultAddress",
            type: "boolean",
            required: false,
            description:
              "Whether to store this address in the default shipping address slot.",
          },
          {
            id: "phoneNumber",
            type: "string",
            required: false,
            description: "The phone Number of the shipping address.",
          },
          {
            id: "companyName",
            type: "string",
            required: false,
            description: "The company name of the shipping address.",
          },
          {
            id: "prefix",
            type: "string",
            required: false,
            description: "The prefix of the shipping address.",
          },
          {
            id: "selectedCountry",
            type: "string",
            required: false,
            description:
              "The country code of the shipping address. If selectedCountry is sent in the request then it takes precedence over country.",
          },
          {
            id: "selectedState",
            type: "string",
            required: false,
            description:
              "The state ISO alpha-2 code of the shipping address. If selectedState is sent in the request then it takes precedence over state.",
          },
          {
            id: "state_ISOCode",
            type: "string",
            required: false,
            description: "The state ISO alpha-4 code of the shipping address.",
          },
        ],
      },
    ],
    example: {
      dynamicPropertyMaritalStatus: "Married",
      firstName: "kim",
      lastName: "anderson",
      password: "kim1234",
      GDPRProfileP13nConsentGranted: false,
      gender: "female",
      receiveEmail: "yes",
      dateOfBirth: "",
      email: "kim@example.com",
      shippingAddresses: [
        {
          lastName: "Black",
          country: "United States",
          types: [{ id: "ss-100001" }],
          address3: "",
          address2: "",
          city: "Wake Forest",
          prefix: "",
          address1: "405 Example Street",
          defaultCountryCode: "US",
          postalCode: "27587",
          jobTitle: "",
          companyName: "",
          county: "",
          isDefaultAddress: true,
          suffix: "",
          selectedCountry: "US",
          firstName: "Jack",
          phoneNumber: "555123456",
          alias: "Address",
          faxNumber: "",
          middleName: "",
          state: "North Carolina",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
        {
          lastName: "Hill",
          country: "United States",
          types: [{ id: "ss-100001" }],
          address3: "",
          address2: "",
          city: "Wake Forest",
          prefix: "",
          address1: "415 Example Road",
          defaultCountryCode: "US",
          postalCode: "27587",
          jobTitle: "",
          companyName: "",
          county: "",
          isDefaultAddress: false,
          suffix: "",
          selectedCountry: "US",
          firstName: "Jill",
          phoneNumber: "55512345",
          alias: "Address##0",
          faxNumber: "",
          middleName: "",
          state: "North Carolina",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
      ],
    },
  },
  {
    displayName: "createProfileAddress",
    requestParameters: [
      {
        id: "addressType",
        type: "string",
        required: false,
        description: "The alias name of the shipping address.",
      },
      {
        id: "firstName",
        type: "string",
        required: true,
        description: "The first name of the shipping address.",
      },
      {
        id: "lastName",
        type: "string",
        required: true,
        description: "The last name of the shipping address.",
      },
      {
        id: "address1",
        type: "string",
        required: true,
        description: "The address line 1 of the shipping address.",
      },
      {
        id: "address2",
        type: "string",
        required: false,
        description: "The address line 2 of the shipping address.",
      },
      {
        id: "city",
        type: "string",
        required: true,
        description: "The city of the shipping address.",
      },
      {
        id: "county",
        type: "string",
        required: false,
        description: "The county code of the shipping address.",
      },
      {
        id: "state",
        type: "string",
        required: true,
        description: "The state code of the shipping address.",
      },
      {
        id: "postalCode",
        type: "string",
        required: true,
        description: "The postal Code of the shipping address.",
      },
      {
        id: "country",
        type: "string",
        required: true,
        description: "The country of the shipping address.",
      },
      {
        id: "isDefaultShippingAddress",
        type: "boolean",
        required: false,
        description:
          "Whether to store this address in the default shipping address slot.",
      },
      {
        id: "isDefaultBillingAddress",
        type: "boolean",
        required: false,
        description:
          "Whether to store this address in the default billing address slot.",
      },
      {
        id: "phoneNumber",
        type: "string",
        required: false,
        description: "The phone Number of the shipping address.",
      },
      {
        id: "companyName",
        type: "string",
        required: false,
        description: "The company name of the shipping address.",
      },
    ],
    example: {
      addressType: "Address",
      firstName: "Jack",
      lastName: "Black",
      address1: "405 Example Street",
      address2: "",
      address3: "",
      city: "Wake Forest",
      county: "",
      state: "NC",
      postalCode: "27587",
      country: "US",
      isDefaultShippingAddress: true,
      phoneNumber: "555123456",
      companyName: "",
    },
  },
  {
    displayName: "deleteProfileAddress",
    requestParameters: [
      {
        id: "addressId",
        type: "string",
        required: true,
        description: "The ID of the address.",
      },
    ],
    example: { addressId: "1234567" },
  },
  {
    displayName: "getCurrentProfile",
    requestParameters: [
      {
        id: "expand",
        type: "string",
        required: false,
        description:
          "This field determines the additional properties to be returned. Possible value for this query parameter is ‘accessRights’ to include accessRights of the current profile.",
      },
      {
        id: "includedRoles",
        type: "string",
        required: false,
        description:
          "This field determines if only organizational roles or all roles are to be returned for the current profile. Default value is 'organizationalRolesForCurrentOrganization’. Possible values are 'organizationalRolesForCurrentOrganization’, 'allRolesForCurrentOrganization’.",
      },
      {
        id: "_filterKey",
        type: "object",
        required: false,
        description: "filterKey object",
        internalPropperties: [
          {
            id: "filterKey",
            type: "string",
            required: false,
            description: "filterKey Id",
          },
        ],
      },
    ],
    example: {
      _filterKey: { filterKey: "OSFCurrentProfile" },
      expand: "accessRights",
      includedRoles: "allRolesForCurrentOrganization",
    },
  },
  {
    displayName: "getProfileAddress",
    requestParameters: [
      {
        id: "addressId",
        type: "string",
        required: true,
        description: "The ID of the address.",
      },
    ],
    example: { addressId: "1234567" },
  },
  {
    displayName: "getProfileSavedCard",
    requestParameters: [
      {
        id: "savedCardId",
        type: "string",
        required: true,
        description: "The savedCardId of the card to be retrevied",
      },
    ],
    example: { savedCardId: "usercc10001" },
  },
  {
    displayName: "listProfileSavedCards",
    requestParameters: [
      {
        id: "allCards",
        type: "boolean",
        required: false,
        description:
          "This value is set to true, if inactive cards are also expected in the response.",
      },
      {
        id: "allGateways",
        type: "boolean",
        required: false,
        description:
          "This value is set to true, if the cards from disabled gateways are also expected in the response.",
      },
      {
        id: "allSites",
        type: "boolean",
        required: false,
        description:
          "This value is set to true, if the cards from non-current site are also expected in the response.",
      },
    ],
    example: { allCards: true, allGateways: true, allSites: true },
  },
  {
    displayName: "removeSavedCardFromProfile",
    requestParameters: [
      {
        id: "savedCardId",
        type: "string",
        required: true,
        description: "The savedCardId of the card which is to be removed",
      },
    ],
    example: { savedCardId: "usercc10001" },
  },
  {
    displayName: "saveCardToProfile",
    requestParameters: [
      {
        id: "cardType",
        type: "string",
        required: true,
        description: "Card type. e.g. visa.",
      },
      {
        id: "cardNumber",
        type: "string",
        required: true,
        description: "Card number",
      },
      {
        id: "cardCVV",
        type: "string",
        required: true,
        description: "Card secret pin.",
      },
      {
        id: "nameOnCard",
        type: "string",
        required: true,
        description: "Name on the card.",
      },
      {
        id: "expiryMonth",
        type: "string",
        required: true,
        description: "Card expiry month.",
      },
      {
        id: "expiryYear",
        type: "string",
        required: true,
        description: "Card expiry year.",
      },
      {
        id: "nickname",
        type: "string",
        required: false,
        description: "The nick name for the card.",
      },
      {
        id: "setAsDefault",
        type: "boolean",
        required: false,
        description:
          "The flag to determine whether the card needs to be set as default card for the profile.",
      },
      {
        id: "customProperties",
        type: "object",
        required: false,
        description:
          "Custom object with dynamic properties. This will be passed to the webhook request.",
      },
      {
        id: "billingAddress",
        type: "object",
        required: true,
        description: "The billing address details.",
        internalPropperties: [
          {
            id: "firstName",
            type: "string",
            required: true,
            description: "First name.",
          },
          {
            id: "middleName",
            type: "string",
            required: false,
            description: "Middle name.",
          },
          {
            id: "lastName",
            type: "string",
            required: true,
            description: "Last name.",
          },
          {
            id: "prefix",
            type: "string",
            required: false,
            description: "Name prefix.",
          },
          {
            id: "suffix",
            type: "string",
            required: false,
            description: "Name suffix.",
          },
          {
            id: "jobTitle",
            type: "string",
            required: false,
            description: "Job title.",
          },
          {
            id: "companyName",
            type: "string",
            required: false,
            description: "Company name.",
          },
          {
            id: "address1",
            type: "string",
            required: true,
            description: "Address line 1.",
          },
          {
            id: "address2",
            type: "string",
            required: false,
            description: "Address line 2.",
          },
          {
            id: "address3",
            type: "string",
            required: false,
            description: "Address line 3.",
          },
          {
            id: "city",
            type: "string",
            required: true,
            description: "City.",
          },
          {
            id: "phoneNumber",
            type: "string",
            required: false,
            description: "Phone number.",
          },
          {
            id: "faxNumber",
            type: "string",
            required: false,
            description: "Fax number.",
          },
          {
            id: "email",
            type: "string",
            required: false,
            description: "Email address.",
          },
          {
            id: "county",
            type: "string",
            required: false,
            description: "County.",
          },
          {
            id: "state",
            type: "string",
            required: true,
            description: "State code.",
          },
          {
            id: "country",
            type: "string",
            required: true,
            description: "Country code.",
          },
          {
            id: "postalCode",
            type: "string",
            required: true,
            description: "Postal code.",
          },
          {
            id: "alias",
            type: "string",
            required: false,
            description: "Address alias.",
          },
        ],
      },
    ],
    example: {
      cardType: "visa",
      cardNumber: "4123567812341111",
      cardCVV: "123",
      nameOnCard: "card2",
      expiryMonth: "03",
      expiryYear: "2021",
      nickname: "visa - 1111",
      setAsDefault: true,
      customProperties: { prop2: "value2", prop1: "value1" },
      billingAddress: {
        firstName: "Kim",
        middleName: "",
        lastName: "Anderson",
        prefix: "",
        suffix: "",
        jobTitle: "",
        companyName: "",
        address1: "21 Cedar Ave",
        address2: "",
        address3: "",
        city: "Syracuse",
        phoneNumber: "212-555-1977",
        faxNumber: "",
        email: "test@example.com",
        county: "",
        state: "NY",
        country: "US",
        postalCode: "13202",
        alias: "",
      },
    },
  },
  {
    displayName: "updateDefaultProfileAddress",
    requestParameters: [
      {
        id: "addressId",
        type: "string",
        required: true,
        description: "The ID of the address.",
      },
    ],
    example: { addressId: "1234567" },
  },
  {
    displayName: "updateProfile",
    requestParameters: [
      {
        id: "firstName",
        type: "string",
        required: false,
        description: "The first name of the profile.",
      },
      {
        id: "lastName",
        type: "string",
        required: false,
        description: "The last name of the profile.",
      },
      {
        id: "email",
        type: "string",
        required: false,
        description: "The email address of the profile.",
      },
      {
        id: "locale",
        type: "string",
        required: false,
        description: "The locale of the profile.",
      },
      {
        id: "password",
        type: "string",
        required: false,
        description: "The password of the profile.",
      },
      {
        id: "receiveEmail",
        type: "string",
        required: false,
        description:
          "The string representation of whether the user wants to receive email or not.",
      },
      {
        id: "GDPRProfileP13nConsentGranted",
        type: "boolean",
        required: false,
        description:
          "If user has given consent for his/her profile information to be used for personalization purposes.",
      },
      {
        id: "gender",
        type: "string",
        required: false,
        description: "The gender of the profile user.",
      },
      {
        id: "dateOfBirth",
        type: "string",
        required: false,
        description: "The date of birth of the profile user.",
      },
      {
        id: "shippingAddress",
        type: "object",
        required: false,
        description: "Default shipping addresses associated with profile.",
        internalPropperties: [
          {
            id: "repositoryId",
            type: "string",
            required: false,
            description: "The repository ID of the shipping address.",
          },
          {
            id: "alias",
            type: "string",
            required: false,
            description: "The alias of the shipping address.",
          },
          {
            id: "firstName",
            type: "string",
            required: true,
            description: "The first name of the shipping address.",
          },
          {
            id: "lastName",
            type: "string",
            required: true,
            description: "The last name of the shipping address.",
          },
          {
            id: "address1",
            type: "string",
            required: true,
            description: "The address line 1 of the shipping address.",
          },
          {
            id: "address2",
            type: "string",
            required: false,
            description: "The address line 2 of the shipping address.",
          },
          {
            id: "address3",
            type: "string",
            required: false,
            description: "The address line 3 of the shipping address.",
          },
          {
            id: "city",
            type: "string",
            required: true,
            description: "The city of the shipping address.",
          },
          {
            id: "county",
            type: "string",
            required: false,
            description: "The county code of the shipping address.",
          },
          {
            id: "state",
            type: "string",
            required: true,
            description: "The state code of the shipping address.",
          },
          {
            id: "postalCode",
            type: "string",
            required: true,
            description: "The postal Code of the shipping address.",
          },
          {
            id: "country",
            type: "string",
            required: true,
            description: "The country of the shipping address.",
          },
          {
            id: "isDefaultAddress",
            type: "boolean",
            required: false,
            description:
              "Whether to store this address in the default shipping address slot.",
          },
          {
            id: "phoneNumber",
            type: "string",
            required: false,
            description: "The phone Number of the shipping address.",
          },
          {
            id: "companyName",
            type: "string",
            required: false,
            description: "The company name of the shipping address.",
          },
          {
            id: "prefix",
            type: "string",
            required: false,
            description: "The prefix of the shipping address.",
          },
          {
            id: "selectedCountry",
            type: "string",
            required: false,
            description:
              "The country code of the shipping address. If selectedCountry is sent in the request then it takes precedence over country.",
          },
          {
            id: "selectedState",
            type: "string",
            required: false,
            description:
              "The state ISO alpha-2 code of the shipping address. If selectedState is sent in the request then it takes precedence over state.",
          },
          {
            id: "state_ISOCode",
            type: "string",
            required: false,
            description: "The state ISO alpha-4 code of the shipping address.",
          },
        ],
      },
      {
        id: "receiveEmailGlobal",
        type: "boolean",
        required: false,
        description:
          "Whether to receive emails for all sites, if there are multiple sites.",
      },
      {
        id: "GDPRProfileP13nConsentGrantedGlobal",
        type: "boolean",
        required: false,
        description:
          "Whether to consent to GDPR for all sites, if there are multiple sites.",
      },
    ],
    example: {
      firstName: "Jack",
      lastName: "Black",
      email: "jack@example.com",
      locale: "en",
      receiveEmail: "yes",
      GDPRProfileP13nConsentGranted: false,
      gender: "female",
      dateOfBirth: "",
      daytimeTelephoneNumber: "555123456",
      shippingAddress: {
        repositoryId: "1234567",
        alias: "Address",
        firstName: "Jack",
        lastName: "Black",
        address1: "405 Example Street",
        address2: "",
        address3: "",
        city: "Wake Forest",
        county: "",
        state: "North Carolina",
        postalCode: "27587",
        country: "United States",
        isDefaultAddress: true,
        phoneNumber: "555123456",
        prefix: "",
        companyName: "",
        selectedCountry: "US",
        selectedState: "NC",
        state_ISOCode: "US-NC",
      },
      shippingAddresses: [
        {
          repositoryId: "1234567",
          alias: "Address",
          firstName: "Jack",
          lastName: "Black",
          address1: "405 Example Street",
          address2: "",
          address3: "",
          city: "Wake Forest",
          county: "",
          state: "North Carolina",
          postalCode: "27587",
          country: "United States",
          isDefaultAddress: true,
          phoneNumber: "555123456",
          prefix: "",
          companyName: "",
          selectedCountry: "US",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
        {
          alias: "Address##0",
          firstName: "Jill",
          lastName: "Hill",
          address1: "415 Example Road",
          address2: "",
          address3: "",
          city: "Wake Forest",
          county: "",
          state: "North Carolina",
          postalCode: "27587",
          country: "United States",
          isDefaultAddress: false,
          phoneNumber: "55512345",
          prefix: "",
          companyName: "",
          selectedCountry: "US",
          selectedState: "NC",
          state_ISOCode: "US-NC",
        },
      ],
      _dynamicProperty_: "Dynamic Property Value",
      receiveEmailGlobal: true,
    },
  },
  {
    displayName: "createProfileAddress",
    requestParameters: [
      {
        id: "addressId",
        type: "string",
        required: true,
        description: "The repository ID of the shipping address.",
      },
      {
        id: "addressType",
        type: "string",
        required: false,
        description: "The alias name of the shipping address.",
      },
      {
        id: "firstName",
        type: "string",
        required: true,
        description: "The first name of the shipping address.",
      },
      {
        id: "lastName",
        type: "string",
        required: true,
        description: "The last name of the shipping address.",
      },
      {
        id: "address1",
        type: "string",
        required: true,
        description: "The address line 1 of the shipping address.",
      },
      {
        id: "address2",
        type: "string",
        required: false,
        description: "The address line 2 of the shipping address.",
      },
      {
        id: "city",
        type: "string",
        required: true,
        description: "The city of the shipping address.",
      },
      {
        id: "county",
        type: "string",
        required: false,
        description: "The county code of the shipping address.",
      },
      {
        id: "state",
        type: "string",
        required: true,
        description: "The state code of the shipping address.",
      },
      {
        id: "postalCode",
        type: "string",
        required: true,
        description: "The postal Code of the shipping address.",
      },
      {
        id: "country",
        type: "string",
        required: true,
        description: "The country of the shipping address.",
      },
      {
        id: "isDefaultShippingAddress",
        type: "boolean",
        required: false,
        description:
          "Whether to store this address in the default shipping address slot.",
      },
      {
        id: "isDefaultBillingAddress",
        type: "boolean",
        required: false,
        description:
          "Whether to store this address in the default billing address slot.",
      },
      {
        id: "phoneNumber",
        type: "string",
        required: false,
        description: "The phone Number of the shipping address.",
      },
      {
        id: "companyName",
        type: "string",
        required: false,
        description: "The company name of the shipping address.",
      },
    ],
    example: {
      addressId: "1234567",
      addressType: "Address",
      firstName: "Jack",
      lastName: "Black",
      address1: "405 Example Street",
      address2: "",
      address3: "",
      city: "Wake Forest",
      county: "",
      state: "North Carolina",
      postalCode: "27587",
      country: "United States",
      isDefaultAddress: true,
      phoneNumber: "555123456",
      prefix: "",
      companyName: "",
    },
  },
  {
    displayName: "updateProfileSavedCard",
    requestParameters: [
      {
        id: "savedCardId",
        type: "string",
        required: true,
        description: "The savedCardId of the card which is to be updated",
      },
      {
        id: "nickname",
        type: "string",
        required: false,
        description: "The nick name for the card.",
      },
      {
        id: "setAsDefault",
        type: "string",
        required: false,
        description:
          "The flag to determine whether the card needs to be set as default card for the profile.",
      },
    ],
    example: {
      addressId: "1234567",
      addressType: "Address",
      firstName: "Jack",
      lastName: "Black",
      address1: "405 Example Street",
      address2: "",
      address3: "",
      city: "Wake Forest",
      county: "",
      state: "North Carolina",
      postalCode: "27587",
      country: "United States",
      isDefaultAddress: true,
      phoneNumber: "555123456",
      prefix: "",
      companyName: "",
    },
  },
  {
    displayName: "listProfileAddresses",
    requestParameters: [
      {
        id: "offset",
        type: "integer",
        required: false,
        description: "Starting Index",
      },
      {
        id: "limit",
        type: "integer",
        required: false,
        description:
          "Specifies the number of addresses to be fetched starting from offset. In case this is not present, complete list of the addresses are retrieved starting from offset record.",
      },
      {
        id: "queryFormat",
        type: "string",
        required: false,
        description:
          "queryFormat to search on the address properties. Possible values SCIM or null.",
      },
      {
        id: "query",
        type: "string",
        required: false,
        description: "SCIM query to search on the address properties.",
      },
      {
        id: "addressType",
        type: "string",
        required: false,
        description: "Address Type",
      },
      {
        id: "sort",
        type: "string",
        required: false,
        description:
          "This field determines the sort order of the list to be fetched. eg: id:asc",
      },
      {
        id: "totalResults",
        type: "boolean",
        required: false,
        description:
          "Tells whether to include total and totalResults in the SCIM query.By default the value is true",
      },
    ],
    example: { limit: 2, query: "city eq 'Dewitt'" },
  },
];
